# Form implementation generated from reading ui file './qt/ElHdrEditWnd.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HdrEditDialog(object):
    def setupUi(self, HdrEditDialog):
        HdrEditDialog.setObjectName("HdrEditDialog")
        HdrEditDialog.resize(729, 575)
        self.verticalLayout = QtWidgets.QVBoxLayout(HdrEditDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=HdrEditDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.typesList = QtWidgets.QComboBox(parent=self.frame)
        self.typesList.setObjectName("typesList")
        self.gridLayout.addWidget(self.typesList, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=HdrEditDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headersTbl = QtWidgets.QTableView(parent=self.frame_2)
        self.headersTbl.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AnyKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.headersTbl.setCornerButtonEnabled(False)
        self.headersTbl.setObjectName("headersTbl")
        self.headersTbl.horizontalHeader().setVisible(True)
        self.headersTbl.horizontalHeader().setCascadingSectionResizes(False)
        self.headersTbl.horizontalHeader().setHighlightSections(True)
        self.headersTbl.horizontalHeader().setStretchLastSection(False)
        self.headersTbl.verticalHeader().setVisible(False)
        self.headersTbl.verticalHeader().setCascadingSectionResizes(True)
        self.headersTbl.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.headersTbl)
        self.verticalLayout.addWidget(self.frame_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=HdrEditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(HdrEditDialog)
        self.buttonBox.accepted.connect(HdrEditDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(HdrEditDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HdrEditDialog)

    def retranslateUi(self, HdrEditDialog):
        _translate = QtCore.QCoreApplication.translate
        HdrEditDialog.setWindowTitle(_translate("HdrEditDialog", "Dialog"))
        self.label.setText(_translate("HdrEditDialog", "Select Type:"))
